### ISSUE TITLE
How to understand herd privacy in using bit string?

### ISSUE THREAD

**Issue by echenknox** [w3c/vc-bitstring-status-list#54] opened 2023-02-06 02:34 UTC
Each holder's VC has its RLC issued at a different time. The bit string can change from time to time. That means different VC can have a different bit string in their RLCs. If two different RLC's bit strings have a different value in the same index, it doesn't mean any of the bit string is tempered. It only means one bit value may be changed between the time issuing the first RLC and the second RLC.

**Comment by msporny** [comment] 2023-12-29 16:27
Yes, I believe your interpretation is correct. To add to the explanation, there are TWO VCs that matter:

1. The VC containing the `credentialStatus` field, which points to the `BitstringStatusListCredential` (let's call this the "base VC").
2. The`BitstringStatusListCredential`, which contains the bit string (let's call this the "status list VC").

The "base VC" is issued and given to the Holder, which then eventually passes it on to a Verifier. The Verifier will then download the "status list VC" at some point in time and will check a particular bit in the bitstring. The bitstring in the "status list VC" can change from time to time as the status of the "base VC" changes. This is perfectly fine.

Note that the "base VC" does change at all, but the "status list VC" does change over time (by design).

**Comment by msporny** [comment] 2023-12-29 16:33
Closing this issue since the question has been answered.

**Closed by msporny** 2023-12-29 16:33 UTC
Labels: question, before-CR
